language: python
cache: pip
python: 2.7
install:
  - pip install -e .
  - pip install coveralls
  - pip install tox
  - pip install webtest
  - pip install tox-pytest-summary

before_script:
  - mysql -e 'create database myapp_test;' # username: "root", password: ""
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - psql -c 'create database travis_ci_test;' -U postgres

script: tox -v

services:
  # MySQL is started by default
  - mongodb

addons:
    postgresql: "9.3"

after_success:
  - coveralls

after_script:
  - tox-pytest-summary

sudo: false

addons:
  apt:
    packages:
    - libmysqlclient-dev
    - python3-dev
